### ISSUE TITLE
Manifest errors after installing 3.2.0

### ISSUE THREAD

**Issue by rreeves2** [Mist-Automation-Programmability/mist_browser_extension#58]
I've installed this extension in Chrome for the first time and followed the instructions found here. The extension icon doesn't show up in the browser window, and it's producing two Manifest-related errors:

- Unrecognized manifest key 'browser_specific_settings'. 
  - Highlighted code:

```
  "browser_specific_settings": {
    "gecko": {
      "update_url": "https://raw.githubusercontent.com/tmunzer/mist_browser_extension/main/firefox_updates.json"
    }
  },
```

- Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
- Highlighted code:

`  "manifest_version": 2,`

**Comment by tmunzer** [comment]
Hi Robert,

These are just warning messages that should not block the extension.
Chrome is still supporting manifest V2 and Google postponed the transition to V3 many times (https://developer.chrome.com/blog/more-mv2-transition/). 
I'm currently using the extension on Chrome Version 115.0.5790.114

However, by default the extension is not showed in the Chrome bar, and you must pin it to keep it in the bar (or you should be able to access it by clicking the "extension" icon in the Chrome bar):
<img width="350" alt="image" src="https://github.com/tmunzer/mist_browser_extension/assets/5295774/2d89e7b1-ff75-488e-9045-2c1155bd052f">

**Comment by rreeves2** [comment]
::facepalm:: Yup, that was it, thank you for the quick response!
