### ISSUE TITLE
Extension stopped working and unable to re-load

### ISSUE THREAD

**Issue by andypando** [Mist-Automation-Programmability/mist_browser_extension#60]
Browser extension stopped working for me this week in Chrome. When I went into Extensions to manage it, there were a bunch of error. I removed the installed extension, re-downloaded the .zip, expanded it and tried to reload and I get the following:
Failed to load extension
File
~/Desktop/mist_browser_extension-main
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by tmunzer** [comment]
Hi Andy,

It seems you are trying to load the source code, and not the extension code.
Can you download the file mist_extension-3.3.1.zip from https://github.com/Mist-Automation-Programmability/mist_browser_extension/releases/tag/3.3.1 and try again?

Also, if the extension is not showing in the browser top bar, please check this issue: https://github.com/Mist-Automation-Programmability/mist_browser_extension/issues/58

**Comment by andypando** [comment]
That fixed it... was weird that it just died on Monday. Thanks Thomas!!

Thank You,
*Andy Pandolfino*
615-614-3231

**Comment by tmunzer** [comment]
Thanks for the confirmation!
