### ISSUE TITLE
Typo in main.js for device ZTP password.

### ISSUE THREAD

**Issue by cdwcody** [Mist-Automation-Programmability/mist_browser_extension#83]
The main.js file contains a minor typo with 'password' misspelled as 'passowrd', as seen in attached screenshot. This was seen in extension version 4.0.0.

![image](https://github.com/user-attachments/assets/4ee946d6-b614-46de-9dd2-555b130d4cc6)

The typos look to be in the following files prior to packing the Javascript:
https://github.com/Mist-Automation-Programmability/mist_browser_extension/blob/d039f1ba6ea262cf2d87baf2d8d81bf861acfb89/angular/src/app/pages/api/manage/ztp_password/ztp_passowrd.component.html#L4

https://github.com/Mist-Automation-Programmability/mist_browser_extension/blob/d039f1ba6ea262cf2d87baf2d8d81bf861acfb89/angular/src/app/pages/api/manage/ztp_password/ztp_passowrd.component.ts#L16

**Comment by tmunzer** [comment]
fixed in v4.1.0
